[package]
name = "xiee-installer"
version.workspace = true
edition.workspace = true

[[bin]]
name = "xiee-installer"
path = "src/main.rs"

[dependencies]
xiee-gui = { path = "../xiee-gui" }
egui.workspace = true
eframe.workspace = true
env_logger.workspace = true
serde.workspace = true
serde_json.workspace = true